name: Monitor Website Changes

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install urlwatch
          # pip install keyrings.alt # Keep this commented out for now

      - name: Verify urlwatch.yaml content
        run: |
          echo "--- Verifying urlwatch.yaml content: ---"
          cat urlwatch.yaml
          echo "--- End of urlwatch.yaml content ---"

      - name: Run urlwatch (stdout only) and capture output
        id: urlwatch_run
        # Run urlwatch, forcing ONLY stdout reporter. Redirect output.
        # Use --verbose for more detailed output.
        # continue-on-error: true allows the workflow to proceed even if urlwatch exits non-zero.
        continue-on-error: true
        run: urlwatch --urls urls.yaml --config urlwatch.yaml --report stdout --verbose &> urlwatch_output.txt

      - name: Send email notification if changes/errors detected
        # Only run this step if the previous step 'failed' (i.e., urlwatch exited non-zero).
        # This typically happens on NEW, CHANGED, or ERROR states.
        if: steps.urlwatch_run.outcome == 'failure'
        uses: dawidd6/action-send-mail@v3
        with:
          # SMTP server configuration (Office365)
          server_address: smtp.office365.com
          server_port: 587
          # Credentials from GitHub Secrets
          username: george@hyperion-partners.co.uk
          password: ${{ secrets.URLWATCH_EMAIL_PASSWORD }}
          # Email details
          subject: "urlwatch: Changes Detected / Error Occurred"
          # Use the captured output file as the email body
          body_file: urlwatch_output.txt
          to: george@hyperion-partners.co.uk
          from: george@hyperion-partners.co.uk
          # Connection security: 'secure: true' should enable STARTTLS for port 587 with this action
          secure: true
